vision_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vision_logs.urls')),
]

vision_logs/urls.py
from django.urls import path
from . import views



app_name = 'vision_logs'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('new_topics/', views.new_topics, name='new_topics'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),

]

vision_logs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Content(models.Model):
    content = models.OneToOneField(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    def __str__(self):
        return f'{self.text}'

vision_logs/forms.py
from django import forms
from .models import Topic, Content
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class ContentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ['text']

        labels = {'text': 'Content:'}

        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Email Address'}))
    first_name = forms.CharField(label='', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'First Name'}))
    last_name = forms.CharField(label='', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Last Name'}))

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'User Name'
        self.fields['username'].label = ''
        self.fields['username'].help_text = '<span class="form-text text-muted"><small>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</small></span>'

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = '<ul class="form-text text-muted small"><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul>'

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = '<span class="form-text text-muted"><small>Enter the same password as before, for verification.</small></span>'

vision_logs/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from vision_logs.models import Topic
from vision_logs.forms import TopicForm,ContentForm


# Create your views here.

def index(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You are now logged in')
            return redirect('vision_logs:index')
        else:
            messages.success(request, 'Invalid credentials')
            return redirect('vision_logs:index')
    else:

        return render(request, 'vision_logs/index.html', {})

def topics(request):

    topics = Topic.objects.all().order_by('date_added')
    context = {'topics': topics}
    return render(request, 'vision_logs/topics.html', context)

def new_topics(request):
    """Add a new topic."""

    if request.method != 'POST':
         form = TopicForm()
         content_form = ContentForm()
    else:
        form = TopicForm(data=request.POST)
        content_form = ContentForm(data=request.POST)
    if form.is_valid():
        topic = form.save()
        new_content = content_form.save(commit=False)
        new_content.content = topic  # Link content to the newly created topic
        new_content.save()
        return redirect('vision_logs:topics')
    context = {'form': form, 'content_form': content_form}
    return render(request, 'vision_logs/new_topics.html', context)
'''
def new_content(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = ContentForm()
    else:
        form  = ContentForm(data=request.POST)
    if form.is_valid():
        new_content = form.save(commit=False)
        new_content.content = topic
        new_content.save()
        return redirect('vision_logs:topics')
    # Display a blank or invalid form.
    context = {'topic': topic, 'form': form }
    return render(request, 'vision_logs/new_topics.html', context)
'''
def logout_user(request):
    logout(request)
    messages.success(request, 'You are now logged out')
    return redirect('vision_logs:index')

def register_user(request):
    return render(request, 'vision_logs/register.html', {})

vision_logs/templates/vision_logs/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>vision</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
      {% include 'vision_logs/navbar.html' %}
      <div class="container">
            <br/>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                      {{message}}
                      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}

            {% endblock %}
       </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

vision_logs/templates/vision_logs/index.html
{% extends 'vision_logs/base.html' %}

{% block content %}

<div class="col-md-6 offset-md-3 ">
    {% if user.is_authenticated %}
        <h1>VISION LOG</h1>
    {% else %}
        <h1>Login</h1>
        <br/>
        <form method="POST" action="{% url 'vision_logs:index' %}">
            {% csrf_token %}
            <form>
        <div class="mb-3">

            <input type="text" class="form-control" name="username"
            placeholder="Username" required>

          </div>
          <div class="mb-3">

            <input type="password" class="form-control"
                   name="password" placeholder="Password" required>
          </div>

          <button type="submit" class="btn btn-secondary">Login</button>
        </form>

            </form>
        </div>
    {% endif %}

{% endblock %}

vision_logs/templates/vision_logs/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand" href="{% url 'vision_logs:index' %}">VISION LOG</a>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'vision_logs:logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link " href="{% url 'vision_logs:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'vision_logs:index' %}">Login</a>
          </li>
        {% endif %}

        <li class="nav-item">
          <a class="nav-link active" aria-current="page"  href="#">Topic</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Update Topic</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Edit</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

vision_logs/templates/vision_logs/new_topics.html
{% extends "vision_logs/base.html" %}
{% block content %}
<p>Add a new topic:</p>
<div>
    <form action="{% url 'vision_logs:new_topics' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ content_form.as_p}}
        <button name="submit">Add New Content</button>
    </form>
</div>


{% endblock content %}

vision_logs/templates/vision_logs/register.html
{% extends 'vision_logs/base.html' %}

{% block content %}
    <h1>REGISTER</h1>
{% endblock %}

vision_logs/templates/vision_logs/topics.html
{% extends 'vision_logs/base.html' %}  {# Extend your base template if you have one #}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'vision/topics.css' %}" xmlns="http://www.w3.org/1999/html"
      xmlns="http://www.w3.org/1999/html">

<div style="overflow-x: auto">
<table>
<tr class="new1">
     <th class="head" style="width: 10%">S/N</th>
     <th class="head" style="width: 10%">Date</th>
     <th class="head" style="width: 15%">Topic</th>
     <th class="head" style="width: 65%">Content</th>
</tr>

{% for topic in topics%}
    <tr class="new1">
        <td>{{topic.id}}</td>
        <td class="two">{{topic.date_added|date:'M d, Y'  }}</td>
        <td class="three">{{ topic.text }} VISION</td>
        <td class="four">{{ topic.content }}</td>
    </tr>
{% endfor %}
</table>
</div>










{% endblock content %}